create database BD_Desapega
default character set utf8
default collate utf8_general_ci;

CREATE TABLE LOGIN(
ID_LOGIN INT NOT NULL AUTO_INCREMENT,
EMAIL_LOGIN VARCHAR(48) UNIQUE NOT NULL,
SENHA_LOGIN VARCHAR(100) NOT NULL,

PRIMARY KEY(ID_LOGIN)
);

CREATE TABLE USUARIO(
ID_USUARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(48) NOT NULL,
SENHA INT(40) UNIQUE NOT NULL,
EMAIL VARCHAR(48) UNIQUE NOT NULL,
TELEFONE VARCHAR(11),
ID_LOGIN INT NOT NULL,

PRIMARY KEY(ID_USUARIO),
FOREIGN KEY (ID_LOGIN) REFERENCES LOGIN(ID_LOGIN)
);

CREATE TABLE DOACOES(
ID_ITEM INT NOT NULL AUTO_INCREMENT,
NOME_ITEM VARCHAR(48) NOT NULL,
CATEGORIA_ITEM VARCHAR(40) NOT NULL,
DESCRICAO_ITEM VARCHAR(256) NOT NULL,
ID_USUARIO INT NOT NULL,
CIDADE VARCHAR(50),
BAIRRO VARCHAR(50),
IMAGEM LONGBLOB NOT NULL,

PRIMARY KEY(ID_ITEM),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);




