ALTER TABLE login
DROP COLUMN SENHA_LOGIN;

ALTER TABLE login
ADD COLUMN SENHA_LOGIN VARCHAR(100) NOT NULL;

ALTER TABLE usuario
DROP COLUMN SENHA;

ALTER TABLE usuario
ADD COLUMN SENHA VARCHAR(100) NOT NULL;
